<?php

// Plugin definition
$plugin = array(
  'title' => t('Vertical Tabs'),
  'category' => t('Jnet Custom'),
  'icon' => 'jnetverttabs.png',
  'theme' => 'jnetverttabs',
  'css' => 'jnetverttabs.css',
  'regions' => array(
  	'top_full' => t('Top Full Width'),
	'top' => t('Top'),
	'tabs' => t('Vertical Tabs'),
	'tab1' => t('Tab 1'),
	'tab2' => t('Tab 2'),
	'tab3' => t('Tab 3'),
	'tab4' => t('Tab 4'),
	'tab5' => t('Tab 5'),
	'tab6' => t('Tab 6'),
	'tab7' => t('Tab 7'),
	'tab8' => t('Tab 8'),

	'bottom_full' => t('Bottom Full Width'),
	'bottom' => t('Bottom')
  ),
);
