<?php

/**
 * Implements hook_menu().
 */
function jnet_a_menu() {
  $items['a/%'] = array(
    'page callback' => 'jnet_a_redirect',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function jnet_a_redirect($arg) {
  $nid = db_select('feeds_item', 'f')->fields('f', array('entity_id'))->condition('f.guid', $arg)->execute()->fetchField();
  if ($nid) {
    drupal_goto("node/{$nid}");
  } else {
    // See if we can get any info via Patchbay API.
    $args = explode('_', $arg);
    $response = json_decode(file_get_contents("http://patchbay.journeyon.net/api/type?nid={$args[0]}"));
    if (isset($response->type)) {
      switch ($response->type) {

        // For patchbay_content, get the Short URL field.
        case 'patchbay_content':
          $short_url = json_decode(file_get_contents("http://patchbay.journeyon.net/api/short_url?nid={$args[0]}"));
          drupal_goto($short_url->short_url);
          break;

        // For media and media_series, send them to /media.
        case 'media':
        case 'media_series':
          drupal_goto('media');
          break;
      }
    }
  }

  drupal_set_message('We could not find the requested content.');
  drupal_goto("<front>", array(), 301);
}
