<?php

/**
 * Implements hook_menu().
 */
function jnet_a_menu() {
  $items['a/%'] = array(
    'page callback' => 'jnet_a_redirect',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function jnet_a_redirect($arg) {
  $nid = db_select('feeds_item', 'f')->fields('f', array('entity_id'))->condition('f.guid', $arg)->execute()->fetchField();
  if ($nid) {
    drupal_goto("node/{$nid}");
  } else {
    drupal_set_message('We could not find the requested content.');
    drupal_goto("<front>");
  }
}
