<?php

/**
 * Set a param.
 * @param custom key
 * @param custom value
 */
function param_set($key, $value) {
  db_merge('param')
    ->key(array('name' => $key))
    ->fields(array('value' => serialize($value)))
    ->execute();
  return;
}

/**
 * Get a param.
 * @param custom key
 * @return the custom value on success or FALSE on failure
 */
function param_get($key) {
  $value = db_select('param')
    ->fields('param', array('value'))
    ->condition('name', $key)
    ->range(0, 1)
    ->execute()
    ->fetchField();
  return unserialize($value);
}
