<?php

// Plugin definition
$plugin = array(
  'title' => t('Mixed Col'),
  'category' => t('Jnet Custom'),
  'icon' => 'jnetmixcol.png',
  'theme' => 'jnetmixcol',
  'css' => 'jnetmixcol.css',
  'regions' => array(
	'top_full' => t('Top Full Width'),
	'top' => t('Top'),
	'left1' => t('Left side 1'),
	'right1' => t('Right side 1'),
	'middle_full' => t('Middle Full Width'),
	'middle' => t('Middle'),
	'left2' => t('Left side 2'),
	'right2' => t('Right side 2'),
	'middle2' => t('Middle 2'),
	'left3' => t('Left side 3'),
	'right3' => t('Right side 3'),
	'left4' => t('Left side 4'),
	'right4' => t('Right side 4'),
	'left5' => t('Left side 5'),
	'right5' => t('Right side 5'),
	'bottom_full' => t('Bottom Full Width'),
	'bottom' => t('Bottom')
  ),
);
